### ISSUE TITLE
Can we get a Windows version?

### ISSUE THREAD

**Issue by ifeldshteyn** [woozzu/py-leveldb#38]
This doesn't compile with python3.6.  

**pip install plyvel** in Windows - we cannot compile the sh file. 

If we skip the sh config it will die with...

plyvel/_plyvel.cpp(703): fatal error C1083: Cannot open include file: 'leveldb/db.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\XXXX\anaconda2\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXXX\\AppData\\Local\\Temp\\pip-install-48s1zj2o\\plyvel_f788a8e6897944a995be82fd231d5eec\\setup.py'"'"'; __file__='"'"'C:\\Users\\XXXX\\AppData\\Local\\Temp\\pip-install-48s1zj2o\\plyvel_f788a8e6897944a995be82fd231d5eec\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\XXXX\AppData\Local\Temp\pip-record-ei3qmp0j\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\XXXX\anaconda2\Include\plyvel' Check the logs for full command output.
